export const BuySellActionTypes = {
    BUY_SELL_COMPANY_CHANGE: "BUY_SELL_COMPANY_CHANGE",
    BUY_TAB_CHANGE: "BUY_TAB_CHANGE",
    MARKET_PRICE_CHANGE: "MARKET_PRICE_CHANGE",
    SHARE_QUANTITY_CHANGE: "SHARE_QUANTITY_CHANGE",
    TARGET_PRICE_CHANGE: "TARGET_PRICE_CHANGE",
}