export const StockDataActionTypes = {
    FETCH_STOCK_DATA: "FETCH_STOCK_DATA",
    FETCH_STOCK_DATA_SUCCESS: "FETCH_STOCK_DATA_SUCCESS",
    FETCH_STOCK_DATA_ERROR: "FETCH_STOCK_DATA_ERROR",
    TOGGLE_WATCHLIST: "TOGGLE_WATCHLIST",
}