export const TransactionActionTypes = {
    ADD_TO_TRANSACTIONS: "ADD_TO_TRANSACTIONS",
    ADD_TO_PENDING_BLOCKED_AMOUNT: "ADD_TO_PENDING_BLOCKED_AMOUNT",
    SUBSTRACT_FROM_PENDING_BLOCKED_AMOUNT: "SUBSTRACT_FROM_PENDING_BLOCKED_AMOUNT",
    DELETE_PENDING_TRANSACTION: "DELETE_PENDING_TRANSACTION",
    ADD_TO_PENDING_BLOCKED_STOCKS: "ADD_TO_PENDING_BLOCKED_STOCKS",
    SUBSTRACT_FROM_PENDING_BLOCKED_STOCKS: "SUBSTRACT_FROM_PENDING_BLOCKED_STOCKS",
    ADD_TO_BLOCKED_TRANSACTION: "ADD_TO_BLOCKED_TRANSACTION",
    REMOVE_FROM_BLOCKED_TRANSACTION: "REMOVE_FROM_BLOCKED_TRANSACTION",
    MODIFY_PENDING_TRANSACTION: "MODIFY_PENDING_TRANSACTION",
}