export const WatchlistActionTypes = {
    CREATE_WATCHLIST: "CREATE_WATCHLIST",
    DELETE_WATCHLIST: "DELETE_WATCHLIST",
    RENAME_WATCHLIST: "RENAME_WATCHLIST",
    ADD_COMPANY_TO_WATCHLIST: "ADD_COMPANY_TO_WATCHLIST",
    REMOVE_COMPANY_FROM_WATCHLIST: "REMOVE_COMPANY_FROM_WATCHLIST",
}